language: emacs-lisp
# Emacs fails to build using the latest Trusty image on Travis
# See https://github.com/travis-ci/travis-ci/issues/9073
sudo: required
dist: trusty
group: deprecated-2017Q4
# See https://github.com/flycheck/emacs-travis/issues/22
# cache:
#   - directories:
#       - "$HOME/emacs/"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=26.3
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - make compile
  - make lint
  - make test
notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
